name: muroappmod
description: The Gorgeous OTP

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  simple_animations: ^1.3.3

  numeric_keyboard: ^1.0.0

  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3

  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4

  cupertino_icons: ^0.1.3

  rxdart: ^0.24.1
  image_picker: ^0.6.7+7
  mime_type: ^0.3.2

  mapbox_gl: ^0.9.0
  url_launcher: ^5.5.0
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  intl_phone_field:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3
  

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/